apiVersion: apps/v1
kind: Deployment                    # 종류
metadata:
  name: hello-client-dempoyment     # deployment - 이름
  labels:                           # deployment 객체에 라벨을 정의
    app: hello-client
spec:                               # deployment 의 스펙에 대한 정의
  replicas: 1                         # replica 갯수
  selector:                           # 파드가 어떤 레이블 (label)을 가지고 있는지 정의
    matchLabels:                      # 묶어질 레이블 정의
      app: hello-client
  template:                         # 파드 템플릿에 대한 정의
    metadata:                         # 파트 템플릿 메타정보
      labels:                            # 파드의 레이블 (label)을 정의
        app: hello-client
    spec:                           # 파드 스펙에 대한 정의
      containers:                     # 컨테이너 정보
        - name: hello-client-container
          image: mycup/spring-cloud-client:latest
          #resources:                # 리소스 정보
          #  limits:                   # 리밋 제한
          #    memory: "128Mi"         # 메모리 제한
          #    cpu: "500m"             # CPU 제한
          ports:                     # 컨테이너 포트 정보
            - containerPort: 80
          env:                       # 컨테이너 환경설정 정보
            - name: EURECA_HOST
              value: "localhost"