apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ads-server
  labels:
    app: hello-ads-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ads-server
  template:
    metadata:
      labels:
        app: hello-ads-server
    spec:
      containers:
        - name: hello-ads-server
          image: mycup/spring-server-ads:latest
          #resources:
          #  limits:
          #    memory: "128Mi"
          #    cpu: "500m"
          ports:
            - containerPort: 8082