server:
  port: ${PORT:8080}
spring:
  application:
    name: mos-server-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  autoconfiguration:
    jackson:
      enabled: true
  circuitbreaker:
    enabled: true

  client:
    config:
      default:
        errorDecoder: com.client.config.GlobalCustomErrorDecoder
    default-to-properties: false
#  client:
#    decode-slash: true
#    config:
#      default:
#        decode: ads.model.APIResponse

logging:
  level:
    root: info
    ads.client: debug # open feign package 로그를 보기 위함.
    com.client.external: debug
