server:
  port: ${PORT:80}
spring:
  application:
    name: mos-server-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      default:
        errorDecoder: com.client.config.GlobalCustomErrorDecoder
        connectionTimeout: 3000
        readTimeout: 3000
    default-to-properties: false

#  client:
#    decode-slash: true
#    config:
#      default:
#        decode: ads.model.APIResponse

logging:
  level:
    root: info
    ads.client: debug # open feign package 로그를 보기 위함.
    com.client.external: debug
